// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Card documents */
interface CardDocumentData {
    /**
     * image field in *Card*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: card.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * title field in *Card*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * details field in *Card*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: card.details
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    details: prismicT.KeyTextField;
}
/**
 * Card document from Prismic
 *
 * - **API ID**: `card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CardDocumentData>, "card", Lang>;
/** Content for days documents */
interface DaysDocumentData {
    /**
     * days field in *days*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: days.days
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    days: prismicT.NumberField;
}
/**
 * days document from Prismic
 *
 * - **API ID**: `days`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DaysDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DaysDocumentData>, "days", Lang>;
export type AllDocumentTypes = CardDocument | DaysDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CardDocumentData, CardDocument, DaysDocumentData, DaysDocument, AllDocumentTypes };
    }
}
